[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [[redirects]]
#  from = "https://example.app"
#  to = "https://example.in"
#  status = 301
#  force = true
#  conditions = {Country = ["IN"]}